name: Gerar EXE

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Baixar projeto
        uses: actions/checkout@v4

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm install

      - name: Build React
        run: npm run build

      - name: Gerar executavel
        run: npx electron-builder --win portable

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Sistema-Atestados
          path: dist
