name: Gerar Executável Windows
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Baixar Projeto
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar Dependências
        run: npm install

      - name: Build do React
        run: npm run build

      - name: Criar Executável
        run: |
          mkdir saida
          npm run dist -- --output saida

      - name: Upload do Sistema
        uses: actions/upload-artifact@v4
        with:
          name: Sistema-Atestados-Windows
          path: saida/
